

const dev = {

  apiGateway:{
    REACT_APP_API_GATEWAY_REGION: process.env.REACT_APP_API_GATEWAY_REGION,
    REACT_APP_API_GATEWAY_URL: process.env.REACT_APP_API_GATEWAY_URL
  },
  cognito: {
    REACT_APP_COGNITO_REGION: process.env.REACT_APP_COGNITO_REGION,
    REACT_APP_COGNITO_USER_POOL_ID: process.env.REACT_APP_COGNITO_USER_POOL_ID,
    REACT_APP_COGNITO_APP_CLIENT_ID: process.env.REACT_APP_COGNITO_APP_CLIENT_ID,
    REACT_APP_COGNITO_IDENTITY_POOL_ID: process.env.REACT_APP_COGNITO_IDENTITY_POOL_ID
  }
};

const prod = {

  apiGateway:{
    REACT_APP_API_GATEWAY_REGION: process.env.REACT_APP_API_GATEWAY_REGION,
    REACT_APP_API_GATEWAY_URL: process.env.REACT_APP_API_GATEWAY_URL
  },
  cognito: {
    REACT_APP_COGNITO_REGION: process.env.REACT_APP_COGNITO_REGION,
    REACT_APP_COGNITO_USER_POOL_ID: process.env.REACT_APP_COGNITO_USER_POOL_ID,
    REACT_APP_COGNITO_APP_CLIENT_ID: process.env.REACT_APP_COGNITO_APP_CLIENT_ID,
    REACT_APP_COGNITO_IDENTITY_POOL_ID: process.env.REACT_APP_COGNITO_IDENTITY_POOL_ID
  }
};

// Default to dev if not set
const config = process.env.REACT_APP_STAGE === 'prod'
  ? prod
  : dev;

export default {

  ...config
};